# Generated by Django 3.0 on 2023-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('reference_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('WPL_reference_number', models.CharField(max_length=8)),
                ('WPL_lead', models.CharField(choices=[('Adam Skeates', 'Adam Skeates'), ('Amber Burton', 'Amber Burton'), ('Andras Doczi', 'Andras Doczi'), ('Andrea Sleap', 'Andrea Sleap'), ('Anjay Chauhan', 'Anjay Chauhan'), ('Bryn Webb', 'Bryn Webb'), ('Chloe Lacy', 'Chloe Lacy'), ('Claire Charles', 'Claire Charles'), ('David Duly', 'David Duly'), ('David Tozer', 'David Tozer'), ('Emma Ames', 'Emma Ames'), ('George Oliphant', 'George Oliphant'), ('Holly Gooderham', 'Holly Gooderham'), ('Ilona Holt', 'Ilona Holt'), ('Jayne Oxenham', 'Jayne Oxenham'), ('Jessica Comer', 'Jessica Comer'), ('Joanne Pearce', 'Joanne Pearce'), ('John Ayres', 'John Ayres'), ('John Godfrey', 'John Godfrey'), ('Kate Penfield', 'Kate Penfield'), ('Katie Mooney', 'Katie Mooney'), ('Kelly Boadas', 'Kelly Boadas'), ('Rachel Ames', 'Rachel Ames'), ('Rebecca  Vinton', 'Rebecca Vinton'), ('Rob Houston', 'Rob Houston'), ('Sally Turner', 'Sally Turner'), ('Sam Kyuma', 'Sam Kyuma'), ('Sam Morant', 'Sam Morant'), ('Simon Wright', 'Simon Wright'), ('Victoria Williams', 'Victoria Williams'), ('Will Garvey', 'Will Garvey')], max_length=200)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('trust', models.CharField(choices=[('HHFT', 'HHFT'), ('UHS', 'UHS'), ('UEL', 'UEL'), ('HHFT & UHS', 'HHFT & UHS'), ('HHCS', 'HHCS'), ('HHFT & UEL', 'HHFT & UEL')], max_length=20)),
                ('project_title', models.TextField()),
                ('project_type', models.CharField(choices=[('CPW', 'CPW'), ('Contracting/Tendering', 'Contracting/Tendering'), ('Catalogue Submission', 'Catalogue Submission'), ('CIP/Cost Avoidance', 'CIP/Cost Avoidance'), ('Contract Only (if 12 months or over please add to the Contracts Register)', 'Contract Only (if 12 months or over please add to the Contracts Register)')], max_length=80)),
                ('supplier', models.TextField(blank=True)),
                ('entered_by', models.CharField(max_length=80)),
            ],
        ),
    ]
