# Generated by Django 3.0 on 2023-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_logged',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_type',
            field=models.CharField(choices=[('CPW', 'CPW'), ('Contracting/Tendering', 'Contracting/Tendering'), ('Catalogue Submission', 'Catalogue Submission'), ('CIP/Cost Avoidance', 'CIP/Cost Avoidance'), ('Contract Only', 'Contract Only')], max_length=80),
        ),
    ]
