# Generated by Django 3.0 on 2023-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20230906_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_logged',
            field=models.DateField(auto_now_add=True),
        ),
    ]
