# Generated by Django 3.0 on 2023-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20230906_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
