# Generated by Django 3.0 on 2023-08-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPW',
            fields=[
                ('CPW_PK', models.BigAutoField(primary_key=True, serialize=False)),
                ('WPL_reference', models.CharField(max_length=8)),
                ('trust', models.CharField(choices=[('HHFT', 'HHFT'), ('UHS', 'UHS'), ('UEL', 'UEL'), ('HHCS', 'HHCS')], max_length=20)),
                ('date_added_to_cpw', models.DateTimeField(auto_now_add=True)),
                ('project_title', models.CharField(max_length=80)),
                ('cpw_rationale', models.CharField(choices=[('Extreme Urgency', 'Extreme Urgency'), ('Direct Award due to Technical or Clinical Requirement', 'Direct Award due to Technical or Clinical Requirement'), ('Renewal with existing supplier/Interim arrangement', 'Renewal with existing supplier/Interim arrangement'), ('Retrospective Approval', 'Retrospective Approval'), ('Centrally Mandated Requirement', 'Centrally Mandated Requirement')], max_length=200)),
                ('supplier', models.CharField(max_length=80)),
                ('total_cpw_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('division', models.CharField(choices=[('Multiple Divisions', 'Multiple Divisions'), ('F&CS Division', 'F&CS Division'), ('Medicine Division', 'Medicine Division'), ('Surgery Division', 'Surgery Division'), ('Corporate Division', 'Corporate Division'), ('Private Patients', 'Private Patients'), ('Central', 'Central'), ('Trust Balance Sheet', 'Trust Balance Sheet'), ('MOHHS', 'MOHHS'), ('Trustwide', 'Trustwide'), ('Division A', 'Division A'), ('Division B', 'Division B'), ('Division C', 'Division C'), ('Division D', 'Division D'), ('Trust Headquarters', 'Trust Headquarters'), ('Balance Sheet', 'Balance Sheet'), ('Central Income', 'Central Income'), ('Chilworth Project', 'Chilworth Project'), ('R&D', 'R&D'), ('UEL Theatres', 'UEL Theatres'), ('UEL Estates', 'UEL Estates'), ('UEL Corporate', 'UEL Corporate'), ('HH Contract Services', 'HH Contract Services')], max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('most_senior_approval_received_by', models.CharField(max_length=80)),
                ('date_final_approval_received', models.DateField()),
                ('one_off_purchase', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=80)),
                ('contract_term', models.PositiveSmallIntegerField()),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
