# Generated by Django 3.0 on 2023-09-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activity_entered_by'),
        ('CPW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpw',
            name='reference_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpws', related_query_name='cpw', to='activities.activity'),
        ),
    ]
