# Generated by Django 3.0 on 2023-09-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPW', '0002_auto_20230907_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpw',
            old_name='trust',
            new_name='cpw_trust',
        ),
    ]
