# Generated by Django 3.0 on 2023-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPW', '0003_auto_20230911_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpw',
            old_name='cpw_trust',
            new_name='trust',
        ),
    ]
