# Generated by Django 3.0 on 2023-08-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('contracts_PK', models.BigAutoField(primary_key=True, serialize=False)),
                ('WPL_reference', models.CharField(max_length=8)),
                ('trust', models.CharField(choices=[('HHFT', 'HHFT'), ('UHS', 'UHS'), ('UEL', 'UEL'), ('HHCS', 'HHCS')], max_length=20)),
                ('WPL_category_area', models.CharField(choices=[('Ward Based Consumables', 'Ward Based Consumables'), ('Sterile Intervention Equipment and Associated Consumables', 'Sterile Intervention Equipment and Associated Consumables'), ('Infection Control and Wound Care', 'Infection Control and Wound Care'), ('Orthopaedics, Trauma & Spine, Ophthamology', 'Orthopaedics, Trauma & Spine, Ophthamology'), ("Rehabilitation, Disabled Services, Women's Health & Associated Consumables", "Rehabilitation, Disabled Services, Women's Health & Associated Consumables"), ('Cardio-Vascular, Radiology, Specialist Medicine, Audiology & Pain Management', 'Cardio-Vascular, Radiology, Specialist Medicine, Audiology & Pain Management'), ('Clinical Capital and Diagnostic Devices', 'Clinical Capital and Diagnostic Devices'), ('Office Solutions', 'Office Solutions'), ('Facilities & Catering', 'Facilities & Catering'), ('Estates', 'Estates'), ('Informatics', 'Informatics'), ('Human Resources', 'Human Resources'), ('Pathology', 'Pathology'), ('Corporate', 'Corporate')], max_length=200)),
                ('sub_category', models.CharField(choices=[('Electrodes & Diathermy', 'Electrodes & Diathermy'), ('Enteral / Dietetics', 'Enteral / Dietetics'), ('IV Therapy', 'IV Therapy'), ('Mobile Devices - Pump Drivers, Syringe Admin Infusion', 'Mobile Devices - Pump Drivers, Syringe Admin Infusion'), ('Patient Assessment / Patient Monitoring', 'Patient Assessment / Patient Monitoring'), ('Theatre & General Procedure Packs & Associated Sterile', 'Theatre & General Procedure Packs & Associated Sterile'), ('Theatre Equipment & Staff Protective Consumables', 'Theatre Equipment & Staff Protective Consumables'), ('Theatre Equipment & Surgical Instruments', 'Theatre Equipment & Surgical Instruments'), ('Theatre Patient Temperature Management', 'Theatre Patient Temperature Management'), ('Theatre Sterile Intraoperative & Post Operative Consumables', 'Theatre Sterile Intraoperative & Post Operative Consumables'), ('ENT Consumables', 'ENT Consumables'), ('Dressings & Woundcare', 'Dressings & Woundcare'), ('Infection Control Consumables', 'Infection Control Consumables'), ('Ophthalmology', 'Ophthalmology'), ('Orthopaedics & Associated Consumables', 'Orthopaedics & Associated Consumables'), ('Aides to Daily Living (Rehab)', 'Aides to Daily Living (Rehab)'), ('Continence Inc Bowel Management', 'Continence Inc Bowel Management'), ('Patient Handling', 'Patient Handling'), ('Podiatry, Chiropody & Occupational Therapy', 'Podiatry, Chiropody & Occupational Therapy'), ('Pressure Therapy (inc Bed Frames)', 'Pressure Therapy (inc Bed Frames)'), ("Woman's Health", "Woman's Health"), ('Renal Inc. Urology Equipment & Consumables', 'Renal Inc. Urology Equipment & Consumables'), ('Audiology', 'Audiology'), ('Cardio-vascular, Radiology & Endoscopy', 'Cardio-vascular, Radiology & Endoscopy'), ('Neurology & Pain Management', 'Neurology & Pain Management'), ('Respiratory & Sleep Therapy Equipment', 'Respiratory & Sleep Therapy Equipment'), ('Cancer Services', 'Cancer Services'), ('Capital Leasing', 'Capital Leasing'), ('Device Maintenance', 'Device Maintenance'), ('Capital Replacement Programme', 'Capital Replacement Programme'), ('Clinical equipment rental/hire', 'Clinical equipment rental/hire'), ('Device Rental', 'Device Rental'), ('Stationery', 'Stationery'), ('Furniture', 'Furniture'), ('Catering Consumables', 'Catering Consumables'), ('Catering Food', 'Catering Food'), ('Domestic Management - Paper', 'Domestic Management - Paper'), ('Domestic Management - Janitorial', 'Domestic Management - Janitorial'), ('Non Clinical Clothing, Protective Clothing, Curtains, Bedding, Haberdashery', 'Non Clinical Clothing, Protective Clothing, Curtains, Bedding, Haberdashery'), ('Polymer (Plastics)', 'Polymer (Plastics)'), ('Design & Build', 'Design & Build'), ('states Goods & Services', 'Estates Goods & Services'), ('Construction', 'Construction'), ('Estates Capital Equipment', 'Estates Capital Equipment'), ('I.T Software', 'I.T Software'), ('I.T Hardware', 'I.T Hardware'), ('I.T Consultancy', 'I.T Consultancy'), ('Temporary Staffing', 'Temporary Staffing'), ('Insourcing Services', 'Insourcing Services'), ('Training Services', 'Training Services'), ('Pathology Consumables', 'Pathology Consumables'), ('Pathology Managed Services', 'Pathology Managed Services'), ('Pathology Equipment Maintenance', 'Pathology Equipment Maintenance'), ('Equipment Purchase', 'Equipment Purchase'), ('Reagent Rental', 'Reagent Rental'), ('Software', 'Software'), ('Managed Services', 'Managed Services'), ('Finance & Audit services', 'Finance & Audit services'), ('Independent Sector', 'Independent Sector'), ('Consultancy Services', 'Consultancy Services'), ('Research & Development', 'Research & Development'), ('Training Services', 'Training Services')], max_length=200)),
                ('project_title', models.TextField()),
                ('description', models.TextField()),
                ('division', models.CharField(choices=[('Multiple Divisions', 'Multiple Divisions'), ('F&CS Division', 'F&CS Division'), ('Medicine Division', 'Medicine Division'), ('Surgery Division', 'Surgery Division'), ('Corporate Division', 'Corporate Division'), ('Private Patients', 'Private Patients'), ('Central', 'Central'), ('Trust Balance Sheet', 'Trust Balance Sheet'), ('MOHHS', 'MOHHS'), ('Trustwide', 'Trustwide'), ('Division A', 'Division A'), ('Division B', 'Division B'), ('Division C', 'Division C'), ('Division D', 'Division D'), ('Trust Headquarters', 'Trust Headquarters'), ('Balance Sheet', 'Balance Sheet'), ('Central Income', 'Central Income'), ('Chilworth Project', 'Chilworth Project'), ('R&D', 'R&D'), ('UEL Theatres', 'UEL Theatres'), ('UEL Estates', 'UEL Estates'), ('UEL Corporate', 'UEL Corporate'), ('HH Contract Services', 'HH Contract Services')], max_length=200)),
                ('route_to_market', models.CharField(choices=[('Placeholder', 'Placeholder')], default='Placeholder', max_length=20)),
                ('department', models.CharField(max_length=80)),
                ('agreement_type', models.CharField(choices=[('Placeholder', 'Placeholder')], max_length=200)),
                ('personal_info', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('contract_term', models.PositiveSmallIntegerField()),
                ('supplier', models.TextField()),
                ('contract_start', models.DateField()),
                ('extension', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('extension_months', models.PositiveSmallIntegerField()),
                ('notice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('notice_days', models.PositiveSmallIntegerField()),
                ('contract_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('indexation_clause', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('WPL_lead', models.CharField(max_length=200)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
