# Generated by Django 3.0 on 2023-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='agreement_type',
            field=models.CharField(choices=[('Construction Contract', 'Construction Contract'), ('Goods or Services', 'Goods or Services'), ('I.T Contract', 'I.T Contract'), ('Maintenance of Equipment Contract', 'Maintenance of Equipment Contract'), ('Maintenance of Estate Contract', 'Maintenance of Estate Contract'), ('NHSSC - National Pricing Matrix', 'NHSSC - National Pricing Matrix'), ('Operating/Finance Lease', 'Operating/Finance Lease'), ('Rebate Agreement', 'Rebate Agreement')], max_length=200),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='route_to_market',
            field=models.CharField(choices=[('Consortium Arrangement', 'Consortium Arrangement'), ('Direct Award via Framework', 'Direct Award via Framework'), ('Direct Award/Negotiation/CPW', 'Direct Award/Negotiation/CPW'), ('Framework - Mini Competition', 'Framework - Mini Competition'), ('Intra-NHS', 'Intra-NHS'), ('Local Tender', 'Local Tender'), ('NHSSC Category Towers', 'NHSSC Category Towers'), ('Request for Quotation', 'Request for Quotation'), ('Contract Extension', 'Contract Extension')], max_length=250),
        ),
    ]
